### ISSUE TITLE
ProjectGrep without parameters

### ISSUE THREAD

**Issue by tuxflo** [yuki-yano/fzf-preview.vim#110]
In the "normal" fzf I often make use of the custom function "RG" (https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration) to start a search and then enter some strings. Is there a way to achieve the same behaviour in fzf-preview too?
`:FzfPreviewProjectGrep .` is not working since it is using the fuzzy search too (which RG doesn't) and also it seems that this does not respect the default ignored files by `rg`.

Thanks in advance,
tuxflo

**Comment by yuki-yano** [comment]
Sorry for the delay in replying.
I introduced fzf.vim and actually tried to run RG command because I had time.
It may take some time to implement, as we did not expect this kind of usage in our development.
However, I think it's a feature that has a lot of potential, so I'd like to consider implementing it. Thank you very much.

**Comment by yuki-yano** [comment]
There may be some bugs, but I have implemented `FzfPreviewProjectCommandGrep` on a trial basis.
There seems to be a performance problem, so I'll try to improve it.

**Comment by yuki-yano** [comment]
Fixed 3ac74085adc4922b5bb1a4c058c69d7371cb2d94
