### ISSUE TITLE
Buffers preview is not working

### ISSUE THREAD

**Issue by lourenci** [yuki-yano/fzf-preview.vim#28]
Thanks for the plugin.

Is there some config I'm missing? When I try to execute `FzfPreviewBuffers`, the error bellow happens:

![image](https://user-images.githubusercontent.com/2339362/74057703-413a1f80-49c3-11ea-97f3-05066a8ba8fb.png)

**Comment by heimann** [comment]
I seem to be getting the same error when trying to execute:
- `FzfPreviewBuffers`
- `FzfPreviewMruFiles`

FWIW `let files = systemlist(g:fzf_preview_filelist_command)` works if I run it in command mode. I also tried explicitly setting fzf_preview_filelist_command to `'rg --files --hidden --follow --no-messages -g \!"* *"'` from the docs which didn't help.

**Comment by errinlarsen** [comment]
It's a typo. You can fix easily for yourself...

Looksy at [lines 60 & 61 in autload/fzf_preview.vim](https://github.com/yuki-ycino/fzf-preview.vim/blob/master/autoload/fzf_preview.vim#L56-L62). Line 61 should read, `return s:convert_for_fzf(buffers)` (it currently incorrectly lists "files" instead of "buffers"

**Comment by heimann** [comment]
> It's a typo. You can fix easily for yourself...
> 
> Looksy at [lines 60 & 61 in autload/fzf_preview.vim](https://github.com/yuki-ycino/fzf-preview.vim/blob/master/autoload/fzf_preview.vim#L56-L62). Line 61 should read, `return s:convert_for_fzf(buffers)` (it currently incorrectly lists "files" instead of "buffers"

Nice! Made a PR to fix it. Thank you 🙏
