### ISSUE TITLE
[Feature request] Sorting

### ISSUE THREAD

**Issue by kristijanhusak** [yuki-yano/fzf-preview.vim#60]
Hi,

i was wondering if there is a way to provide some kind of sorting to the entries?
For example, for buffers, i would like to have an option to sort them descending, where newer buffers would come first.

**Comment by yuki-yano** [comment]
Vim doesn't store the history of the buffer, so it seems difficult to implement it easily as a plugin function.
If possible, please consider creating and using a new resource in fzf-preview.vim.
(I don't have any documentation about this, but I want to add more.)

Also, if this issue is solved by fzf, I consider implementation.
https://github.com/junegunn/fzf.vim/issues/100

**Comment by zoomido** [comment]
Well this issue is solved in fzf.vim https://github.com/junegunn/fzf.vim/commit/852cfa0c11d5661d79ed1faf1cc211b3c6ef7b00
Would it be possible to implement it somehow?
Sorting of buffers in MRU is something I really miss from fzf.vim.
