### ISSUE TITLE
:FzfPreviewBuffers does not show terminal sessions

### ISSUE THREAD

**Issue by lynndylanhurley** [yuki-yano/fzf-preview.vim#61]
**Expected behavior**: should show the open terminal sessions alongside the open buffers.

**Current behavior**: only files are shown in the buffer list.

This is something that works with fzf.vim that I've become reliant on. Without this feature I'm unable to locate open terminal sessions after the buffer window closes, which happens often when I'm jumping around a lot. So I end up creating a bunch of new sessions instead and lose all of my open REPLs, logs, command history, etc.

It would be great if `:FzfPreviewBuffers` listed all of the active terminal sessions alongside the open buffers.

**Comment by yuki-yano** [comment]
It is difficult to add because of the current implementation of Buffers.

Since `:edit {file_path}` is being executed at the time of selection, it is not possible to move to a non-file buffer.
Also, because the preview is executed in the shell, the preview cannot be displayed.

If all buffers are supported, I have to add new commands to the plugin.
Because it is relatively difficult, I will consider whether to implement.

**Comment by yuki-yano** [comment]
Experimental implementation was done in #63.

**Comment by lynndylanhurley** [comment]
Thanks @yuki-ycino ! I'll test #63

**Comment by lynndylanhurley** [comment]
@yuki-ycino thanks so much, #63 completely solves the problem for me. Amazing work 👍

**Comment by yuki-yano** [comment]
I will merge into master in a few days.
Close.
